Adicionando termos de uso na tela de Cadastro
UnBArqDsw2020-2/2020.2_G7_gXchange_Frontend pull request #5
Opened 2021-04-18 23:47 UTC by Rhuancpq

# Adicionando termos de uso na tela de Cadastro

## Descrição 
Escreva uma breve descrição sobre o que o Pull Request resolve

[US04 - Termo de consentimento](https://github.com/UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS/issues/131)

## Porque este Pull Request é necessário?
Pois o usuário precisa concordar com os termos de uso antes utilizar a aplicação

## Critérios de aceitação

- [x] O termo de consentimento é exibido ao usuário durante o cadastro?
- [x] O termo lista como o sistema usuará os dados do usuário?
- [x] O termo lista como o sistema guardará os dados do usuário?
- [x] Só é possível continuar o cadastro se o termo for aceito

2021-04-25 15:35 UTC, igor-paiva requested changes

2021-04-25 15:35 UTC, igor-paiva commented on src/screens/Term/styles.ts
> +  }
Agora que a aplicação tá crescendo mais isso aqui pode zuar outras páginas, vamos mudar isso aqui. Se não me engano dá pra obter o mesmo resultado fazendo um `&.className`.

Mais informações: https://www.sipios.com/blog-tech/how-to-use-styled-components-with-material-ui-in-a-react-app

2021-04-25 15:35 UTC, igor-paiva commented on src/screens/Signup/index.tsx
> +  const [checked, setChecked] = useState(false);
Esse nome não tá descritivo, aproveitar que tem outras mudanças e arrumar

2021-04-26 20:55 UTC, marcelog5 approved these changes

2021-04-30 23:39 UTC, igor-paiva approved these changes

2021-04-30 23:41 UTC, merged