Visualizar as informações em um anúncio
UnBArqDsw2020-2/2020.2_G7_gXchange_Frontend pull request #8
Opened 2021-04-25 23:42 UTC by marcelog5

# Adicionando funcionalidade visualizar as informações em um anúncio

## Descrição 
Escreva uma breve descrição sobre o que o Pull Request resolve

[US14 - Visualizar as informações em um anúncio](https://github.com/UnBArqDsw2020-2/2020.2_G7_gXchange_DOCS/issues/118)

## Porque este Pull Request é necessário?
Pois é necessário que o usuário possa visualizar as informações de um anúncio

## Critérios de aceitação

1. [x] Só os anúncios válidos estão sendo mostrados no feed?
2. [x] Possui: título, foto principal, condição, preço (se aplicável), plataforma, se é troca ou venda
4. [x] Sempre que precisar o componente deve requisitar a próxima pagina de requisição.
5. [x] Apenas os dados necessários são retornados da requisição?

2021-04-26 00:40 UTC, igor-paiva reviewed
Algumas coisinhas pra gente arrumar, mas fica pra depois

2021-04-26 00:40 UTC, igor-paiva approved these changes

2021-04-26 00:48 UTC, Rhuancpq requested changes

2021-04-26 00:48 UTC, Rhuancpq commented on src/services/api_ibge.ts
> +export default class APIAdapter {
Trocar o nome da classe

2021-04-30 23:42 UTC, igor-paiva approved these changes

2021-04-30 23:43 UTC, Rhuancpq approved these changes

2021-04-30 23:48 UTC, WashingtonBispo approved these changes
Aprovado

2021-04-30 23:48 UTC, merged